### ISSUE TITLE
A config option for server stop timeout

### ISSUE THREAD

**Issue by ArmanMokammel** [BaoUida2000/BedrockServer2000#3]
When stop command is sent, the wrapper notifies in chat that the server will stop in 10 seconds and then after 10 seconds it proceeds to do so.

So, I have added a new config option which a user can change the timeout of 10 seconds depending on their choice. The example can be:
>>set serverStopTimeout X  //where X can be any positive integer and is in seconds.
>>stop

This will produce in game chat:
Server closing in X seconds

And it will wait for X seconds before stopping the server.
Should I create a pull request for that?

**Comment by BaoUida2000** [comment]
I'll make that! Thanks for suggesting!

**Comment by BaoUida2000** [comment]
I should probably test the code tô.

**Comment by ArmanMokammel** [comment]
> I'll make that! Thanks for suggesting!

Oh I already have some code ready for this. Can do a pull request if you wish.

**Comment by BaoUida2000** [comment]
> > I'll make that! Thanks for suggesting!
> 
> 
> 
> Oh I already have some code ready for this. Can do a pull request if you wish.

Yeah sure! I'll test it

**Comment by ArmanMokammel** [comment]
I have added a pull request.
