### ISSUE TITLE
Loading saved online backups causes program to freeze

### ISSUE THREAD

**Issue by BaoUida2000** [BaoUida2000/BedrockServer2000#4]

**Comment by BaoUida2000** [comment]
hey @ArmanMokammel, which platform do you run the server on? Is it linux? Or Windows?

**Comment by ArmanMokammel** [comment]
@BaoUida2000 I test it on windows and then run the actual server on an ubuntu server with no gui.

**Comment by BaoUida2000** [comment]
@ArmanMokammel does it work on windows? Was there any weird errors on windows that does not show up when running on ubuntu? I just wanna make sure the ửapper works on both platforms.

**Comment by ArmanMokammel** [comment]
I did not see any errors on ubuntu. And I haven't tried a complete run on windows, so will let you know on that later. But so far it seems to be working as expected.

**Comment by BaoUida2000** [comment]
RIght now the Load function only copy the selected backup and overwrite the world folder, it does not delete the world folder beforehand.
```cs
CopyFilesRecursively(backupList[choice - 1].Path, (string)Program.ServerConfigs["worldPath"]);
```
it was supposed to delete the world folder before copying the backup over, but when the server starts, it wuold give errors about missing 5-9 ldb files and the server software tries to fix it itself.

**Comment by BaoUida2000** [comment]
I'm not sure if overwriting is a good solution

**Comment by BaoUida2000** [comment]
well, it may causes problem the other way around, I guess

**Comment by ArmanMokammel** [comment]
Did you check on your previous gui version of the project?

**Comment by ArmanMokammel** [comment]
I have found an issue in windows.... it cannot find the server executable. I think this is due to it being hard coded to "bedrock_server" instead of "bedrock_server.exe"

**Comment by ArmanMokammel** [comment]
![image](https://user-images.githubusercontent.com/22028960/128589552-4c1578e5-d750-4738-8d84-5996e7e3fe1a.png)

**Comment by BaoUida2000** [comment]
ah the server executable, I should allow it to find bedrock_server.exe too

**Comment by BaoUida2000** [comment]
FIxed it, try it again

**Comment by BaoUida2000** [comment]
is that windows 8.1?

**Comment by ArmanMokammel** [comment]
> FIxed it, try it again

Yes it works... and yes I have windows 8.1

**Comment by BaoUida2000** [comment]
Hey I fixed the banlist crash! 🎊

**Comment by ArmanMokammel** [comment]
Awesome... We're having great progress today.

**Comment by ArmanMokammel** [comment]
I did not understand the fix though.

**Comment by BaoUida2000** [comment]
> I did not understand the fix though.

neither do I, there's something wrong with the `System.IO.File.Create()` method so I switched to `System.IO.File.WriteAllText`
This method writes the specified string to a given file path, if the file is not found, a new file is created, so I called that method to write an empty string to the the banlist file.

**Comment by BaoUida2000** [comment]
I think I'll never use `FIle.Create()` ever again and use `File.WriteAlText(string path, "")` instead because every time I use that method an exception is thrown, not sure if I use it wrong or something but if it works, I'll use it.

**Comment by ArmanMokammel** [comment]
We can use `File.WriteAlText(string path, "")` for now... will change it later if needed. This does not affect our program anyway.

**Comment by BaoUida2000** [comment]
found this line in my code I added last month
`//TODO: add "banlistScanInterval" key in configuration file to specify the interval between each scan in seconds`
Might do that later.

**Comment by ArmanMokammel** [comment]
> found this line in my code I added last month
> `//TODO: add "banlistScanInterval" key in configuration file to specify the interval between each scan in seconds`
> Might do that later.

Ok

**Comment by BaoUida2000** [comment]
I just did a bunch of code optimizations and added that ban list scan interval

**Comment by ArmanMokammel** [comment]
Yes I just saw it, seems fine but I have a suggestion. I think the banlist should be scaned whenever a player joins unlike a scan interval, or we could have both as an option.

**Comment by ArmanMokammel** [comment]
We will have to extract the xuid of the player from the console anyways and so we shall also be able to detect when a player joins and then we perform a scan on that player.

**Comment by BaoUida2000** [comment]
yeah it's there in the code, look in Events.cs

**Comment by BaoUida2000** [comment]
it does save players's gamertag and xuid everytime they join, and scan them to look for a match in the banlist, but for nơ it only scan their name, I think I dhould make it scan xuid too so banned players can't just change their name and get away with it

**Comment by BaoUida2000** [comment]
I wrote some bad code so it's not obvious sometimes 😅

**Comment by ArmanMokammel** [comment]
> it does save players's gamertags and XUIDs everytime they join, and scan them to look for a match in the banlist, but for now it only scans their names, I think I should make it scans XUIDs too so banned players can't just change their name and get away with it

Yes, and in this way we can also keep track of the new names banned players changing their username when they will try to join.

**Comment by ArmanMokammel** [comment]
> yeah it's there in the code, look in Events.cs

Yes I got it.

**Comment by BaoUida2000** [comment]
> > it does save players's gamertags and XUIDs everytime they join, and scan them to look for a match in the banlist, but for now it only scans their names, I think I should make it scans XUIDs too so banned players can't just change their name and get away with it
> 
> 
> 
> Yes, and in this way we can also keep track of the new names banned players changing their username when they will try to join.

that thing rarely happens because they can just create another account but I can do the XUOD scan and that too, but how do it know that the banned player changed their name? I still kicks them because it see their XUID in the banlist but how will it know that their name is different than their old name? Maybe some linked stuff in the banlist? I think that is complicated and does not help much

**Comment by BaoUida2000** [comment]
maybe name and xuid mixed in the banlist is good enough, it does kick banned players just fine

**Comment by ArmanMokammel** [comment]
> RIght now the Load function only copy the selected backup and overwrite the world folder, it does not delete the world folder beforehand.
> 
> ```cs
> CopyFilesRecursively(backupList[choice - 1].Path, (string)Program.ServerConfigs["worldPath"]);
> ```
> 
> it was supposed to delete the world folder before copying the backup over, but when the server starts, it wuold give errors about missing 5-9 ldb files and the server software tries to fix it itself.

when I did a backup on my ubuntu server, I did not find any ldb files in the backup folder nor the original world folder.

**Comment by BaoUida2000** [comment]
oh my god I will look into this right now, I'm pretty sure it worked nỏmal on my pc last time, I think I did something wrong with the backup code

**Comment by ArmanMokammel** [comment]
> oh my god I will look into this right now, I'm pretty sure it worked nỏmal on my pc last time, I think I did something wrong with the backup code

My bad, I actually though db was a file. Then i realised db is a folder where the ldb files stored.

**Comment by ArmanMokammel** [comment]
Does our server follow this procedure during backup?
stop server>replace files>restart the server. 
Thsi could be a fix for this backup issue for now I think.

**Comment by BaoUida2000** [comment]
there are 2 types of backup, type 1 is offline backup and is pretty easy to perform, it happens when the server is not running and all the wrapper has to do is copy the whole world folder to the backup directory, the secons type is online backup, it happens while the server is running and is very complicated, it first runs the `save hold` command, then `save query` until the server returns the file list, it then parses that list into different kinds of paths to copy all the specified files to a new backup created in the backup directory, then run `save resume` to complete the backup.

**Comment by ArmanMokammel** [comment]
> there are 2 types of backup, type 1 is offline backup and is pretty easy to perform, it happens when the server is not running and all the wrapper has to do is copy the whole world folder to the backup directory, the secons type is online backup, it happens while the server is running and is very complicated, it first runs the `save hold` command, then `save query` until the server returns the file list, it then parses that list into different kinds of paths to copy all the specified files to a new backup created in the backup directory, then run `save resume` to complete the backup.

This is when we perform the backup.... I have not seen any issues with this in my ubuntu server.

**Comment by ArmanMokammel** [comment]
Does the loading of the backup work correctly?

**Comment by ArmanMokammel** [comment]
@BaoUida2000 Okay so I have dug deep into your code and I think it should just replace the entire worlds folder, not just overriding it.

**Comment by BaoUida2000** [comment]
> Does the loading of the backup work correctly?
> 
> 
> 
> Edit: Perhaps the bedrock server software is not capable of reloading backups on the fly.

I code it to restart the server when loading backups.

idk why github allows you to edit other people's comments lol

**Comment by BaoUida2000** [comment]
> @BaoUida2000 Okay so I have dug deep into your code and I think it should just replace the entire worlds folder, not just overriding it.
> 
> 
> 
> Edit: As the server will be restarting, the after loading the backup, this should be safe to do. I will try to do a pull request soon on this.

It's really late right now where I live so I don't have enough time, I'll try to start looking further into this tomorrow morning or as soon as I can.

**Comment by ArmanMokammel** [comment]
> > @BaoUida2000 Okay so I have dug deep into your code and I think it should just replace the entire worlds folder, not just overriding it.
> > Edit: As the server will be restarting, the after loading the backup, this should be safe to do. I will try to do a pull request soon on this.
> 
> It's really late right now where I live so I don't have enough time, I'll try to start looking further into this tomorrow morning or as soon as I can.

Sure!

**Comment by BaoUida2000** [comment]
bruh I closed it?

**Comment by BaoUida2000** [comment]
didn't mean to do that, I'll test the code right now, see if it works

**Comment by BaoUida2000** [comment]
oh, I saw it, there's a pull request linked

**Comment by ArmanMokammel** [comment]
Nvm... it can be reopened

**Comment by BaoUida2000** [comment]
can you explain to me how did you fix this?

**Comment by BaoUida2000** [comment]
I wasn't able to do this before, I tried deleting the world folder before copying backup files to, but the server would just give the missing ldb files error

**Comment by BaoUida2000** [comment]
this time it does not give any error

**Comment by BaoUida2000** [comment]
oh no, after I load a saved backup, console input doesn't work anymore

**Comment by ArmanMokammel** [comment]
Alright so in offline backup... if we talk about doing stuff manually, we first delete our main world folder and get the backup world folder in place of that. As we delete the main world folder and replace it with the backup.... there are no files conflicting or missing. Because the backup is acting as a savegame with all the files already there unchanged after the backup. So, during online backup, after the server stops... I delete the main world folder but out server config does not change... then I create the same folder with the value of our already stored `worldPath` and put the backup world files in it.

**Comment by ArmanMokammel** [comment]
For example the folder is `worlds/Arad`. I delete `Arad` with all its subfiles and folders. Then I create it again and put the backup world files in it.

**Comment by ArmanMokammel** [comment]
> oh no, after I load a saved backup, console input doesn't work anymore

Why should that happen... I did not face such issue.

**Comment by ArmanMokammel** [comment]
Did you fix the spelling mistake from my latest pull request?

**Comment by BaoUida2000** [comment]
> Did you fix the spelling mistake from my latest pull request?

your pull request fixed my spelling mistake, there's nothing wrong with it, I think there's some logic issues about requests, I'll try to fix this

**Comment by ArmanMokammel** [comment]
Okay

**Comment by ArmanMokammel** [comment]
Is there something wrong here? Shouldn't the code `Backup.LoadBackup()` be also inside the `if` statement after `StopServer()`

`if (Program.ServerRunning)
				{
					Program.serverInput.WriteLine("say The server is about to restart to load a backup.");
					StopServer();
				}
				else Backup.LoadBackup();`

**Comment by BaoUida2000** [comment]
> Is there something wrong here? Shouldn't the code `Backup.LoadBackup()` be also inside the `if` statement after `StopServer()`
> 
> `if (Program.ServerRunning) { Program.serverInput.WriteLine("say The server is about to restart to load a backup."); StopServer(); }else Backup.LoadBackup();`

The LoadBackup method is called after the server has stopped, and we don't know when will it stop so I made a request bool (loadRequest) and the program will check that bool every time the server process stops, if it's true, call LoadBackup and set it to false

**Comment by BaoUida2000** [comment]
and the input loop in Program.cs skips one loop every time loadRequest is true to avoid sending input to Command.ProcessCommand and send it to the LoadBackup readline.

**Comment by BaoUida2000** [comment]
idk how to explain this my code is shit

**Comment by BaoUida2000** [comment]
but if we run `load` when the server is running, it stops the server, loads backup, then restart server, then input doesn't work anymore
if we run `load` when the server is stopped, it loads a backup and everything works normally with no problems

**Comment by ArmanMokammel** [comment]
> idk how to explain this my code is shit

If it works it just works... programming is like magic with all sorts of weirdness happening.

**Comment by ArmanMokammel** [comment]
> but if we run `load` when the server is running, it stops the server, loads backup, then restart server, then input doesn't work anymore
> if we run `load` when the server is stopped, it loads a backup and everything works normally with no problems

I think the issue might be in the exit or start functions.

**Comment by ArmanMokammel** [comment]
`beginoutputreadline` and `beginoutputerrorline` we start it during `StartServer()` but I think we don't close it `StopServer()`

**Comment by BaoUida2000** [comment]
they automatically stop with the process after the exit procedure

**Comment by ArmanMokammel** [comment]
I don't have windows 10 so I just can't debug this in windows.

**Comment by BaoUida2000** [comment]
I'll try to start debug on linux

**Comment by BaoUida2000** [comment]
this thing is so difficult

**Comment by BaoUida2000** [comment]
it won't start

**Comment by ArmanMokammel** [comment]
Do you have a windows computer though?

**Comment by BaoUida2000** [comment]
Yes, I dual boot windows and linux

**Comment by BaoUida2000** [comment]
but I only run windows 10 to play minecraft windows 10 edition and my pc is too weak to do anything else on windows 10

**Comment by ArmanMokammel** [comment]
> but I only run windows 10 to play minecraft windows 10 edition and my pc is too weak to do anything else on windows 10

I have a similar issue but my laptop is older than your pc and it was win7 which I updated to 8.1 just to stay safe.

**Comment by BaoUida2000** [comment]
I have a core 2 duo and 4gb of DDR2 ram, windows 7 and linux runs great on my pc but windows 10 does not

**Comment by BaoUida2000** [comment]
I used to deal with 2gb of ddr2 for like 4 years

**Comment by BaoUida2000** [comment]
I'm thinking of a solution for this problem, I'll try doing that see if it works, I'll get back when I have the results

**Comment by ArmanMokammel** [comment]
I tried a way if testing... I created a simple exe with the name bedrock_server.exe which prints lol and pauses.... the wrapper treats it as our server and when I load a backup... it sends the stop message which does nothing and I have to manually exit the custom exe and then it lets me load the backup... and then restarts the exe normally. After restarting, the main console freezes for a very short while and then becomes normal.

**Comment by BaoUida2000** [comment]
> I tried a way if testing... I created a simple exe with the name bedrock_server.exe which prints lol and pauses.... the wrapper treats it as our server and when I load a backup... it sends the stop message which does nothing and I have to manually exit the custom exe and then it lets me load the backup... and then restarts the exe normally. After restarting, the main console freezes for a very short while and then becomes normal.

The server program has an exit command which runs the exist procedure and then closes itself

**Comment by ArmanMokammel** [comment]
> > I tried a way if testing... I created a simple exe with the name bedrock_server.exe which prints lol and pauses.... the wrapper treats it as our server and when I load a backup... it sends the stop message which does nothing and I have to manually exit the custom exe and then it lets me load the backup... and then restarts the exe normally. After restarting, the main console freezes for a very short while and then becomes normal.
> 
> The server program has an exit command which runs the exist procedure and then closes itself

I can't run this server on win8.1 so a custom made simple exe acted as one. Then I tried doing online backup.

**Comment by ArmanMokammel** [comment]
> > > I tried a way if testing... I created a simple exe with the name bedrock_server.exe which prints lol and pauses.... the wrapper treats it as our server and when I load a backup... it sends the stop message which does nothing and I have to manually exit the custom exe and then it lets me load the backup... and then restarts the exe normally. After restarting, the main console freezes for a very short while and then becomes normal.
> > 
> > 
> > The server program has an exit command which runs the exist procedure and then closes itself
> 
> I can't run this server on win8.1 so a custom made simple exe acted as one. Then I tried doing online backup.

But I did not encounter any error. And it became normal.

**Comment by BaoUida2000** [comment]
here's my solution
so I removed this line
![image](https://user-images.githubusercontent.com/67570424/128621914-7d3a0cba-8fa6-406b-826e-385481f2dd5f.png)
and everything works fine, except the wrapper still takes normal input when loading a backup once before reading input for the LoadBackup method.
![image](https://user-images.githubusercontent.com/67570424/128621943-d628e59f-7961-4e30-ad2d-07f341a58eb6.png)
Now what we need to do is skip 1 input loop after executing the `load` command, but I haven't figured out how yet.

Do you have any better solution?

**Comment by ArmanMokammel** [comment]
Currently in a class... will look at it when I become free.

**Comment by BaoUida2000** [comment]
fixed it, idk how but this worked
![image](https://user-images.githubusercontent.com/67570424/128622163-0f89b6bc-486c-47d2-a247-44b8d8fabb0e.png)
so I made a property named `LoadRunning` and set it to true/false at the start/end of `LoadBackup()`
```cs
public static bool LoadRunning { get; set; } = false;
```
and edited the input loop like this
```cs
// console input loop
while (true)
{
	if (LoadRequest)
	{
		while (!LoadRunning) { }
		continue;
	}
	Command.ProcessCommand(Console.ReadLine());
}
```

**Comment by BaoUida2000** [comment]
oh no we're stuck again

**Comment by ArmanMokammel** [comment]
The input loop is somehow interfering in our flow.

**Comment by BaoUida2000** [comment]
yes

**Comment by BaoUida2000** [comment]
it's so annoying

**Comment by ArmanMokammel** [comment]
Now what happened

**Comment by BaoUida2000** [comment]
so I edited the input loop again, this time the other way around and much easier to understand, this is the code
```cs
// console input loop
while (true)
{
	Command.ProcessCommand(Console.ReadLine());
	while (LoadRequest || LoadRunning)
	{
		if (!LoadRequest && !LoadRunning) break;
	}
}
```
and now everything works fine, I tested it

**Comment by BaoUida2000** [comment]
I'm gonna commit it right now

**Comment by ArmanMokammel** [comment]
> I'm gonna commit it right now

Okay

**Comment by BaoUida2000** [comment]
ah heck I accidently commited onto your branch, do you have any new commits that haven't been pulled to main? Because I'm gonna merge it into main

**Comment by BaoUida2000** [comment]
merged

**Comment by ArmanMokammel** [comment]
But how did it get resolved. Did not understand the error in the first place

**Comment by BaoUida2000** [comment]
but it's fixed now

**Comment by ArmanMokammel** [comment]
> but it's fixed now

And that's what matters

**Comment by BaoUida2000** [comment]
the problem is the input loop still waiting for input to send to Command.ProcessCommand when LoadBackup is running, so I edited the input loop to just check if LoadRequest or LoadRunning is true, then hangs at the end and wait until the loading is done, then continue the loop and gets inputs from the user

**Comment by ArmanMokammel** [comment]
> but it's fixed now

And that's what matters

**Comment by ArmanMokammel** [comment]
Now I understood.

**Comment by ArmanMokammel** [comment]
I have create two new duscussions where we can do our next conversations.
